export const SET_OFFER_IMAGE = 'SET_OFFER_IMAGE';
export const SET_CURRENT_HEADER_TAB = 'SET_CURRENT_HEADER_TAB';
export const SET_CURRENT_SLIDE = 'SET_CURRENT_SLIDE';
export const SET_ABOUT_IMAGE = 'SET_ABOUT_IMAGE';
export const SET_CONTENT_SLIDE = 'SET_CONTENT_SLIDE';
export const SET_CURRENT_CONTENT_BTN = 'SET_CURRENT_CONTENT_BTN';